{% set name = "nlohmann_json" %}

{% set version = "3.10.2" %}
{% set sha256 = "081ed0f9f89805c2d96335c3acfa993b39a0a5b4b4cef7edb68dd2210a13458c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nlohmann/json/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]
  # The json library is header only, so we do not need
  # to export the compiler run-time libraries.
  # They are just needed during the build to perform some checks.
  ignore_run_exports:
    - libcxx
    - libgcc-ng
    - libstdcxx-ng
    - vc
    - vs2015_runtime

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host: []  # Empty host dependency section

test:
  commands:
    - test -d ${PREFIX}/include/nlohmann  # [unix]
    - test -f ${PREFIX}/include/nlohmann/json.hpp  # [unix]
    - test -f ${PREFIX}/include/nlohmann/json_fwd.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/nlohmann_json/nlohmann_jsonConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/nlohmann_json/nlohmann_jsonConfigVersion.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/nlohmann_json/nlohmann_jsonTargets.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\nlohmann\json.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\include\nlohmann\json_fwd.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\nlohmann_json\nlohmann_jsonConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\nlohmann_json\nlohmann_jsonConfigVersion.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\nlohmann_json\nlohmann_jsonTargets.cmake (exit 1)  # [win]

about:
  home: http://github.com/nlohmann/json
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: JSON for Modern C++
  description: JSON for Modern C++ is a C++11 JSON parser.
  doc_url: http://nlohmann.github.io/json/
  dev_url: http://github.com/nlohmann/json

extra:
  recipe-maintainers:
    - constantinpape
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - basnijholt
